# Week 09 Assignment

**Due date**: Tue, Oct 20 by 3:30pm (submit on Sakai)

## Accessing subsitution matrices from Biopython

The `Bio.Align.subtitution_matrices` module includes representations of commonly used sequence substitution matrices, such as the BLOSUM matrices (BLOSUM62, BLOSUM45, etc) and PAM matrices (PAM250 being the most commonly used).  

To use these representations we need to import the `Bio.Align.subtitution_matrices` and then load the respective substitution matrix (the full of the available subsitution matrices can be viewed here: https://github.com/biopython/biopython/tree/master/Bio/Align/substitution_matrices/data).

In [199]:
from Bio.Align import substitution_matrices

In [200]:
import numpy as np

In [201]:
BLOSUM62 = substitution_matrices.load("BLOSUM62")

In [202]:
BLOSUM62["E", "L"]

-3.0

In [203]:
BLOSUM62["E", "E"]

5.0

In [204]:
PAM250 = substitution_matrices.load("PAM250")

In [205]:
PAM250["E","E"]

4.0

In [206]:
PAM250["E","L"]

-3.0

BLOSUM and PAM matrices are for protein sequences, for nucleotide sequences you can use the matrix designated "NUC.4.4" (all substitutions have equal scores).

In [207]:
NUC4 = substitution_matrices.load("NUC.4.4")

In [208]:
NUC4["A","T"]

-4.0

In [209]:
NUC4["A", "A"]

5.0

## Problem 1 (10 pts)

Write a function, `smith_waterman_matrix` that calculates the scoring matrix for the Smith-Waterman local alignment algorithm.  Your function should take four arguments, as described in the doc string below.

In [217]:
def smith_waterman_matrix(a, b, submatrix, gap_penalty):
    submatrixload = substitution_matrices.load(submatrix)
    matrix = np.empty((0,len(a)+1), int)
    row = np.zeros(len(a)+1)
    matrix = np.append(matrix, np.array([row]), axis=0)
    start = 0
    
    lista = [char for char in a]
    listb = [char for char in b]
    
    for q in range(len(b)):
        row[0] = start
        for p in range(len(a)):
            cell = 0
            x = row[p] + gap_penalty
            y = matrix[-1][p+1] + gap_penalty
            z= matrix[-1][p]
            z += submatrixload[listb[q], lista[p]]
            
            if(x >= y) and (x >= z) and (x >= 0):
                cell = x
            if(y >= x) and (y >= z) and (y >= 0):
                cell = y
            if(z >= x) and (z >= y) and (z >= 0):
                cell = z
                
            row[p+1] = cell
        matrix = np.append(matrix, np.array([row]), axis=0)
    return matrix

Test your function by calculating the scoring matrix for the following alignment problem:

* Align `VEPPLSQE` and `ELPLC` using the BLOSUM62 substitution matrix and a gap penality of -3



In [218]:
print(smith_waterman_matrix("VEPPLSQE","ELPLC","BLOSUM62",-3))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  5.  2.  0.  0.  0.  2.  5.]
 [ 0.  1.  2.  2.  0.  4.  1.  0.  2.]
 [ 0.  0.  0.  9.  9.  6.  3.  0.  0.]
 [ 0.  1.  0.  6.  6. 13. 10.  7.  4.]
 [ 0.  0.  0.  3.  3. 10. 12.  9.  6.]]


## Problem 2 (5 pts)

Using your `smith_waterman_matrix` function above, or working by hand if you were unable to successfuly implement the function, calculate the scoring matrix for the following local alignment problem:

* Align `PAWHEAE` and `HEAGAWGHEE` using the BLOSUM45 substitution matrix and a gap penalty of -8

* What is the best local alignment of these two sequences?

In [219]:
output = smith_waterman_matrix("PAWHEAE", "HEAGAWGHEE","BLOSUM45",-8)
print(output)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 10.  2.  0.  0.]
 [ 0.  0.  0.  0.  2. 16.  8.  6.]
 [ 0.  0.  5.  0.  0.  8. 21. 13.]
 [ 0.  0.  0.  3.  0.  0. 13. 19.]
 [ 0.  0.  5.  0.  1.  0.  5. 12.]
 [ 0.  0.  0. 20. 12.  4.  0.  4.]
 [ 0.  0.  0. 12. 18. 10.  4.  0.]
 [ 0.  0.  0.  4. 22. 18. 10.  4.]
 [ 0.  0.  0.  0. 14. 28. 20. 16.]
 [ 0.  0.  0.  0.  6. 20. 27. 26.]]


The best local alignment of "PAWHEAE" and "HEAGAWGHEE" is:
    AW-HE
    AWGHE