# Week 08 Assignment

**Due date**: Tue, Oct 13 by 3:30pm (submit on Sakai)

## Problem 1

For the alignment problems below, using pencil and paper (or an ipad or other tablet) write down the alignment matrix, including associated costs of the prefix alignments, and the inferred optimal global alignments, using the Needleman-Wunsch algorithm for the following pairs of sequences.  

Use the following cost function:

$$
w(a'_i,b'_i) = \begin{cases}
0 &\text{if } a'_i = b'_i \\
1 & \text{otherwise} 
\end{cases}
$$

Submit your results for this probem by scanning or taking a photo of your work (or saving the results as a PDF or PNG file if working on ipad/tablet) and uploading the image to Sakai.

### Problem 1a (4 pts)

Align: `ACCGA` and `TCCTA`

### Problem 1b (4 pts)

Aign: `AATCG` and `AACGG`

## Problem 2

### Problem 2a (8 pts)

Write a function, `needleman_wunsch`, that computes the alignment cost matrix.

Your function should take as input two strings (representing the sequences to be algined) and two values representing the cost associated with mismatches and the cost associated with gaps. Your function should return a 2D numpy array representing the alignment cost matrix.

In [3]:
import pandas as pd
import numpy as np

In [4]:
def needleman_wunsch(a, b, mismatch_cost, gap_cost):
    matrix = np.empty((0,len(b)+1), int)
    row = np.arange(len(a)+1)
    matrix = np.append(matrix, np.array([row]), axis=0)
    start = 1
    cost = 0
    
    lista = [char for char in a]
    listb = [char for char in b]
    
    for q in range(len(b)):
        row[0] = start
        for p in range(len(a)):
            x = row[p] + gap_cost
            y = matrix[-1][p+1] + gap_cost
            z= matrix[-1][p]
            
            if(listb[q] != lista[p]):
                z += mismatch_cost
            if(x <= y) and (x <= z):
                cost = x
            if(y <= x) and (y <= z):
                cost = y
            if(z <= x) and (z <= y):
                cost = z
                
            row[p+1] = cost
        start+=1
        matrix = np.append(matrix, np.array([row]), axis=0)
        
        
    return matrix

### Problem 2b (4 pts)

Test your `needleman_wunsch` implementation by calculating alignment cost matrices for the alignment in Problems 1a and 1b using the two different mismatch/gap costs below:

* `mismatch_cost = 1`, `gap_cost = 1`
* `mismatch_cost = 1`, `gap_cost = 2`

For either of the alignment problems, do the best alignments change when the gap cost is higher?

In [5]:
needleman_wunsch('ACCGA', 'TCCTA',1,1)

array([[0, 1, 2, 3, 4, 5],
       [1, 1, 2, 3, 4, 5],
       [2, 2, 1, 2, 3, 4],
       [3, 3, 2, 1, 2, 3],
       [4, 4, 3, 2, 2, 3],
       [5, 4, 4, 3, 3, 2]])

In [6]:
needleman_wunsch('ACCGA', 'TCCTA',1,2)

array([[0, 1, 2, 3, 4, 5],
       [1, 1, 2, 3, 4, 5],
       [2, 2, 1, 2, 4, 5],
       [3, 3, 2, 1, 3, 5],
       [4, 4, 4, 3, 2, 4],
       [5, 4, 5, 5, 4, 2]])

In [7]:
needleman_wunsch('AATCG', 'AACGG',1,1)

array([[0, 1, 2, 3, 4, 5],
       [1, 0, 1, 2, 3, 4],
       [2, 1, 0, 1, 2, 3],
       [3, 2, 1, 1, 1, 2],
       [4, 3, 2, 2, 2, 1],
       [5, 4, 3, 3, 3, 2]])

In [8]:
needleman_wunsch('AATCG', 'AACGG',1,2)

array([[0, 1, 2, 3, 4, 5],
       [1, 0, 1, 3, 4, 5],
       [2, 1, 0, 2, 4, 5],
       [3, 3, 2, 1, 2, 4],
       [4, 4, 4, 3, 2, 2],
       [5, 5, 5, 5, 4, 2]])

The best alignments don't change for 1a (ACCGA and TCCTA) because there is only one path 
    from the upper left corner to the lower right corner--the diagonal--i.e. there are no gaps.
    
The best alignments do change for 1b (AATCG and AACGG) because there are 3 unique paths from
    the upper left corner to the lower right corner, meaning there are gaps and more than one 
    possibility when moving up each row.